### PR TITLE
V4 interface changes

### PR DESCRIPTION
**Pull request by keithdoggett**
Change the interface to match coord sys changes in RGeo 3.

### CODE REVIEW

**Review by BuonOmo — COMMENTED** [review]
What happened to `Proj4Data`, was it just not used ?

The rest looks good to me :)

**Comment by keithdoggett** [comment]
@BuonOmo that was part of the `srs_database` module which we removed from the core gem. It was basically the proj extension of that module. But since we are removing it from the core gem we have to remove it from here too since it references classes that were defined in that module.

**Review by BuonOmo — APPROVED** [review]
Of course, thanks for clarifying! LGTM then

**Comment by keithdoggett** [comment]
Thanks @BuonOmo!

**Pull request merged**
