### PR TITLE
Set WKT_TYPE from Proj Version

### PR DESCRIPTION
**Pull request by keithdoggett**
Version 3 uses `PJ_WKT2_2019` as the formatting type for WKT representations. This only available in 6.3+ and breaks at the build stage for 6.2 versions. This PR defines a macro `WKT_TYPE` which will use the newest available version. It also expands on the CI to test against multiple Proj versions.

### CODE REVIEW

**Review by BuonOmo — APPROVED** [review]
Why don't you make that part of the main build job, adding this to the matrix ? If that makes too many jobs you can then `exclude` some. I've done that recently for Oj: https://github.com/ohler55/oj/blob/develop/.github/workflows/CI.yml

Maybe it is less clear though ?

Anyway, do as you feel, LGTM.

**Review by jonlil — APPROVED** [review]
LGTM! :clap: 

Verified that building and installing works inside `ruby:2.7.2-alpine3.11` docker container with proj 6.2.1.

**Comment by BuonOmo** [comment]
@keithdoggett since it is not failing on mac, maybe we can avoid the `continue-on-error` there ?

**Comment by keithdoggett** [comment]
Yes, once the CI passes on the `master` branch I'll make a release.

**Pull request merged**
